version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pentest_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # LABORATORY 1: VULNERABLE
  vulnerable-backend:
    build: ./vulnerable/backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: pentest_db
    depends_on:
      - db

  vulnerable-frontend:
    build: ./vulnerable/frontend
    ports:
      - "5173:5173"
    depends_on:
      - vulnerable-backend

  # LABORATORY 2: SECURE
  secure-backend:
    build: ./secure/backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: pentest_db
      JWT_SECRET: super_secret_key_2026
      PORT: 3000
    depends_on:
      - db

  secure-frontend:
    build: ./secure/frontend
    ports:
      - "5173:5173"
    depends_on:
      - secure-backend
